// +build !ignore_autogenerated

/*
Copyright The Kubernetes Authors.

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/

// Code generated by deepcopy-gen. DO NOT EDIT.

package v1alpha1

import (
	v1 "k8s.io/api/core/v1"
	runtime "k8s.io/apimachinery/pkg/runtime"
)

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *KafkaEventSource) DeepCopyInto(out *KafkaEventSource) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ObjectMeta.DeepCopyInto(&out.ObjectMeta)
	in.Spec.DeepCopyInto(&out.Spec)
	in.Status.DeepCopyInto(&out.Status)
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new KafkaEventSource.
func (in *KafkaEventSource) DeepCopy() *KafkaEventSource {
	if in == nil {
		return nil
	}
	out := new(KafkaEventSource)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *KafkaEventSource) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *KafkaEventSourceConsumer) DeepCopyInto(out *KafkaEventSourceConsumer) {
	*out = *in
	out.Offsets = in.Offsets
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new KafkaEventSourceConsumer.
func (in *KafkaEventSourceConsumer) DeepCopy() *KafkaEventSourceConsumer {
	if in == nil {
		return nil
	}
	out := new(KafkaEventSourceConsumer)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *KafkaEventSourceGroup) DeepCopyInto(out *KafkaEventSourceGroup) {
	*out = *in
	out.Session = in.Session
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new KafkaEventSourceGroup.
func (in *KafkaEventSourceGroup) DeepCopy() *KafkaEventSourceGroup {
	if in == nil {
		return nil
	}
	out := new(KafkaEventSourceGroup)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *KafkaEventSourceList) DeepCopyInto(out *KafkaEventSourceList) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	out.ListMeta = in.ListMeta
	if in.Items != nil {
		in, out := &in.Items, &out.Items
		*out = make([]KafkaEventSource, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new KafkaEventSourceList.
func (in *KafkaEventSourceList) DeepCopy() *KafkaEventSourceList {
	if in == nil {
		return nil
	}
	out := new(KafkaEventSourceList)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *KafkaEventSourceList) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *KafkaEventSourceNet) DeepCopyInto(out *KafkaEventSourceNet) {
	*out = *in
	out.Sasl = in.Sasl
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new KafkaEventSourceNet.
func (in *KafkaEventSourceNet) DeepCopy() *KafkaEventSourceNet {
	if in == nil {
		return nil
	}
	out := new(KafkaEventSourceNet)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *KafkaEventSourceOffsets) DeepCopyInto(out *KafkaEventSourceOffsets) {
	*out = *in
	out.Retry = in.Retry
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new KafkaEventSourceOffsets.
func (in *KafkaEventSourceOffsets) DeepCopy() *KafkaEventSourceOffsets {
	if in == nil {
		return nil
	}
	out := new(KafkaEventSourceOffsets)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *KafkaEventSourceRetry) DeepCopyInto(out *KafkaEventSourceRetry) {
	*out = *in
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new KafkaEventSourceRetry.
func (in *KafkaEventSourceRetry) DeepCopy() *KafkaEventSourceRetry {
	if in == nil {
		return nil
	}
	out := new(KafkaEventSourceRetry)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *KafkaEventSourceSession) DeepCopyInto(out *KafkaEventSourceSession) {
	*out = *in
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new KafkaEventSourceSession.
func (in *KafkaEventSourceSession) DeepCopy() *KafkaEventSourceSession {
	if in == nil {
		return nil
	}
	out := new(KafkaEventSourceSession)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *KafkaEventSourceSpec) DeepCopyInto(out *KafkaEventSourceSpec) {
	*out = *in
	out.Net = in.Net
	out.Consumer = in.Consumer
	out.Group = in.Group
	if in.Sink != nil {
		in, out := &in.Sink, &out.Sink
		*out = new(v1.ObjectReference)
		**out = **in
	}
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new KafkaEventSourceSpec.
func (in *KafkaEventSourceSpec) DeepCopy() *KafkaEventSourceSpec {
	if in == nil {
		return nil
	}
	out := new(KafkaEventSourceSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *KafkaEventSourceSpecSasl) DeepCopyInto(out *KafkaEventSourceSpecSasl) {
	*out = *in
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new KafkaEventSourceSpecSasl.
func (in *KafkaEventSourceSpecSasl) DeepCopy() *KafkaEventSourceSpecSasl {
	if in == nil {
		return nil
	}
	out := new(KafkaEventSourceSpecSasl)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *KafkaEventSourceStatus) DeepCopyInto(out *KafkaEventSourceStatus) {
	*out = *in
	if in.Nodes != nil {
		in, out := &in.Nodes, &out.Nodes
		*out = make([]string, len(*in))
		copy(*out, *in)
	}
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new KafkaEventSourceStatus.
func (in *KafkaEventSourceStatus) DeepCopy() *KafkaEventSourceStatus {
	if in == nil {
		return nil
	}
	out := new(KafkaEventSourceStatus)
	in.DeepCopyInto(out)
	return out
}
