apiVersion: apiextensions.k8s.io/v1beta1
kind: CustomResourceDefinition
metadata:
  name: kafkasources.sources.eventing.knative.dev
spec:
  group: sources.eventing.knative.dev
  names:
    kind: KafkaSource
    listKind: KafkaSourceList
    plural: kafkasources
    singular: kafkasource
  scope: Namespaced
  version: v1alpha1
