apiVersion: eventing.knative.dev/v1alpha1
kind: Subscription
metadata:
  name: ktestevents-subscription
  namespace: myproject
spec:
  channel:
    apiVersion: eventing.knative.dev/v1alpha1
    kind: Channel
    name: hchannel
  subscriber:
    ref:
      apiVersion: serving.knative.dev/v1alpha1
      kind: Service
      name: k-message-dumper

